const data = [
  {
    id: 1,
    title: "Milk",
    name: "Sữa Chua Phúc Bồn",
    price: "50.000 đ",
    start: 5,
    url: require("../assets/images_prd/suachua.png"),
  },
  {
    id: 2,
    title: "Tea",
    name: "Longan Tea (Lotus)",
    price: "50.000 đ",
    start: 5,
    url: require("../assets/images_prd/trathom.png"),
  },
  {
    id: 3,
    title: "Hot Teas",
    name: "Longan Tea (Jasmine)",
    price: "30.000 đ",
    start: 5,
    url: require("../assets/images_prd/trasua.png"),
  },
  {
    id: 4,
    title: "Milk",
    name: "Phuc Long Black Milk Tea",
    price: "45.000 đ",
    start: 5,
    url: require("../assets/images_prd/caphesua.png"),
  },
  {
    id: 5,
    title: "Tea",
    name: "Phuc Long Peach Tea",
    price: "44.000 đ",
    start: 5,
    url: require("../assets/images_prd/tradao.png"),
  },
  {
    id: 6,
    title: "Hot Coffee",
    name: "Ngọc Viễn Đông",
    price: "40.000 đ",
    start: 5,
    url: require("../assets/images_prd/caphe.png"),
  },
  {
    id: 7,
    title: "Hot Coffee",
    name: "Phin Sữa Đá - Năng Lượng",
    price: "45.000 đ",
    start: 5,
    url: require("../assets/images_prd/trasua.png"),
  },
  {
    id: 8,
    title: "Milk",
    name: "Trà Sữa Berry Berry",
    price: "54.000 đ",
    start: 5,
    url: require("../assets/images_prd/traolong.png"),
  },
  {
    id: 9,
    title: "Tea",
    name: "Trà Ô Long Mãng Cầu",
    price: "50.000 đ",
    start: 5,
    url: require("../assets/images_prd/tramangcau.png"),
  },
];
export default data;
