const menuData = [
  {
    id: 1,
    title: "Milk",
    name: "Sữa Chua Phúc Bồn",
    price: 50000,
    start: 5,
    url: require("../assets/images_prd/suachua.png"),
  },
  {
    id: 2,
    title: "Tea",
    name: "Longan Tea (Lotus)",
    price: 50000,
    start: 5,
    url: require("../assets/images_prd/trathom.png"),
  },
  {
    id: 3,
    title: "Hot Teas",
    name: "Longan Tea (Jasmine)",
    price: 30000,
    start: 5,
    url: require("../assets/images_prd/trasua.png"),
  },
  {
    id: 4,
    title: "Milk",
    name: "Phuc Long Black Milk Tea",
    price: 45000,
    start: 5,
    url: require("../assets/images_prd/caphesua.png"),
  },
  {
    id: 5,
    title: "Tea",
    name: "Phuc Long Peach Tea",
    price: 44000,
    start: 5,
    url: require("../assets/images_prd/tradao.png"),
  },
  {
    id: 6,
    title: "Hot Coffee",
    name: "Ngọc Viễn Đông",
    price: 40000,
    start: 5,
    url: require("../assets/images_prd/caphe.png"),
  },
  {
    id: 7,
    title: "Hot Coffee",
    name: "Phin Sữa Đá - Năng Lượng",
    price: 45000,
    start: 5,
    url: require("../assets/images_prd/trasua.png"),
  },
  {
    id: 8,
    title: "Milk",
    name: "Trà Sữa Berry Berry",
    price: 54000,
    start: 5,
    url: require("../assets/images_prd/traolong.png"),
  },
  {
    id: 9,
    title: "Tea",
    name: "Trà Ô Long Mãng Cầu",
    price: 50000,
    start: 5,
    url: require("../assets/images_prd/tramangcau.png"),
  },
  {
    id: 10,
    title: "Milk",
    name: "Phuc Long Milk Tea",
    price: 35000,
    start: 5,
    url: require("../assets/images_prd/caphesua.png"),
  },
  {
    id: 11,
    title: "Milk",
    name: "Phuc Long Milk Tea Special",
    price: 69000,
    start: 5,
    url: require("../assets/images_prd/caphesua.png"),
  },
  {
    id: 12,
    title: "Hot Teas",
    name: "Hot Tea VN",
    price: 33000,
    start: 5,
    url: require("../assets/images_prd/tradau.png"),
  },
];
export default menuData;
